#pragma once

#define TINYSO3_VERSION "0.0.0"

#define TINYSO3_MAJOR_VERSION 0
#define TINYSO3_MINOR_VERSION 0
#define TINYSO3_PATCH_VERSION 0
#define TINYSO3_TWEAK_VERSION "0590244"

#include "config.hpp"

#define TINYSO3_DEFAULT_FLOATING_POINT_TYPE float

#ifdef CONFIG_DEFAULT_FLOATING_POINT_PRECISION_32
#define TINYSO3_DEFAULT_FLOATING_POINT_TYPE float
#elif CONFIG_DEFAULT_FLOATING_POINT_PRECISION_64
#define TINYSO3_DEFAULT_FLOATING_POINT_TYPE double
#elif CONFIG_DEFAULT_FLOATING_POINT_PRECISION_128
#define TINYSO3_DEFAULT_FLOATING_POINT_TYPE long double
#endif
